version: "3.9"

services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    image: esturide_api:latest
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  db_data:
